#!/usr/bin/env python3
"""Have Gemini author a character's DESCRIPTION.md or STYLES.md (the text canon).

The likeness/style canon must be GENERATED by Gemini from the user's raw facts plus
the photos — never hand-authored. This is the text counterpart to
generate_character_sheets.py (which renders the images).

  - --kind description: system_instruction = CHARACTER_TEMPLATE + comic-style skill;
    input = characters/<Name>/FACTS.md (the user's raw prompt) + the reference/ portrait
    cut-outs -> writes <NAME>_DESCRIPTION.md.
  - --kind styles: system_instruction = STYLES_TEMPLATE + comic-style skill;
    input = the generated <NAME>_DESCRIPTION.md + the reference sheet + the styles/
    garment cut-outs -> writes <NAME>_STYLES.md.

REST-based (no SDK), dry-run by default; pass --send to call gemini-3.5-flash.
Requests set store=false (personal photos are not retained server-side).
"""

from __future__ import annotations

import argparse
import os
import re
import time
from pathlib import Path
from typing import Any

from build_character_sheet_prompt import PHOTO_EXTENSIONS, load_house_style
from build_story_prompt import find_description_file, read_text, slugify
from generate_character_sheets import images_in_subdir
from generate_page_images import (
    encode_image,
    post_json,
    redact_image_data,
    write_dry_run_request,
)

DEFAULT_TEXT_MODEL = "gemini-3.5-flash"


def find_facts_file(character_dir: Path) -> Path | None:
    for name in ("FACTS.md", f"{character_dir.name.upper()}_FACTS.md"):
        candidate = character_dir / name
        if candidate.exists():
            return candidate
    matches = sorted(character_dir.glob("*_FACTS.md"))
    return matches[0] if matches else None


def compose_system_instruction(template_text: str, skill_text: str, kind: str) -> str:
    if kind == "styles":
        intro = (
            "You author the STYLE & OUTFIT SNAPSHOT (a markdown file) for a children's-book "
            "character. Fill EVERY section of the styles template below using the character's "
            "reference description, reference sheet, and the attached clothing-segmentation "
            "cut-outs. Describe only what is supported by those inputs; keep it on-model."
        )
        template_label = "# Styles template (fill this exact structure)"
    else:
        intro = (
            "You author the CHARACTER DESIGN REFERENCE (a markdown file) for a children's-book "
            "character. Fill EVERY section of the character template below using the attached "
            "reference photos for appearance and the provided facts for age/height/interests/"
            "colors. Be concrete and consistent; this is the character's canon."
        )
        template_label = "# Character template (fill this exact structure)"

    tail = (
        "Output ONLY the completed markdown document — no preamble, no explanation, and no "
        "surrounding code fences. Apply the comic-style house style below as the art direction."
    )
    sections = [intro, f"{template_label}\n\n{template_text}"]
    if skill_text:
        sections.append("# Comic-style skill (house art style)\n\n" + skill_text)
    sections.append(tail)
    return "\n\n---\n\n".join(sections)


def build_input_blocks(kind: str, name: str, facts_text: str, description_text: str,
                       references: list[Path], reference_sheet: Path | None) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    if kind == "styles":
        blocks.append({"type": "text", "text": (
            f"Character: {name}.\n\nReference description (canon) to stay consistent with:\n\n"
            f"{description_text}\n\nThe first attached image is the rendered reference sheet; the "
            "remaining images are clothing-segmentation cut-outs of the character's real garments. "
            f"Author {name}'s styles snapshot from these."
        )})
        if reference_sheet is not None:
            blocks.append(encode_image(reference_sheet))
        for path in references:
            blocks.append(encode_image(path))
    else:
        blocks.append({"type": "text", "text": (
            f"Character: {name}.\n\nFacts provided by the user (authoritative for age, height, "
            f"weight, interests, favorite colors/characters):\n\n{facts_text}\n\nThe attached images "
            f"are reference photos of {name}. Author {name}'s character design reference from these."
        )})
        for path in references:
            blocks.append(encode_image(path))
    return blocks


def extract_text(response: dict[str, Any]) -> str:
    """Pull the model's text out of an Interactions response (several shapes)."""
    parts: list[str] = []
    direct = response.get("output_text")
    if isinstance(direct, str) and direct.strip():
        parts.append(direct)
    if not parts:
        for step in response.get("steps", []):
            if not isinstance(step, dict) or step.get("type") != "model_output":
                continue
            for block in step.get("content", []):
                if isinstance(block, dict) and block.get("type") in ("text", "output_text"):
                    text = block.get("text") or block.get("data")
                    if isinstance(text, str):
                        parts.append(text)
    out = "\n".join(p.strip() for p in parts if p and p.strip()).strip()
    # Strip accidental code fences.
    if out.startswith("```"):
        out = re.sub(r"^```[a-zA-Z]*\n", "", out)
        out = re.sub(r"\n```$", "", out).strip()
    return out


def selected_dirs(characters_dir: Path, wanted: set[str] | None) -> list[Path]:
    dirs = []
    for d in sorted(p for p in characters_dir.iterdir() if p.is_dir()):
        if wanted is not None and slugify(d.name) not in wanted:
            continue
        dirs.append(d)
    return dirs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--characters-dir", type=Path, default=Path("characters"))
    parser.add_argument("--character", action="append", dest="characters",
                        help="Character name/id (repeatable). Defaults to all.")
    parser.add_argument("--kind", choices=["description", "styles"], default="description")
    parser.add_argument("--facts", help="Inline facts text (overrides FACTS.md) for --kind description.")
    parser.add_argument("--source-subdir", help="Cut-out subfolder (default: reference/ for description, styles/ for styles).")
    parser.add_argument("--skill", type=Path, default=Path("skills/comic-style/SKILL.md"))
    parser.add_argument("--template", type=Path, help="Template to fill (default per kind).")
    parser.add_argument("--model", default=DEFAULT_TEXT_MODEL)
    parser.add_argument("--request-dir", type=Path, default=Path("outputs/character_text_requests"))
    parser.add_argument("--response-dir", type=Path, default=Path("outputs/character_text_responses"))
    parser.add_argument("--send", action="store_true", help="Call the API. Without it, write redacted request JSON only.")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--allow-proxy-auth", action="store_true")
    parser.add_argument("--sleep-seconds", type=float, default=0.0)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.characters_dir.exists():
        raise FileNotFoundError(f"Character directory not found: {args.characters_dir}")

    if args.kind == "styles":
        template_path = args.template or Path("templates/STYLES_TEMPLATE.md")
        images_subdir = args.source_subdir or "styles"
        out_suffix = "STYLES"
    else:
        template_path = args.template or Path("templates/CHARACTER_TEMPLATE.md")
        images_subdir = args.source_subdir or "reference"
        out_suffix = "DESCRIPTION"

    skill_text = args.skill.read_text(encoding="utf-8").strip() if args.skill.exists() else ""
    _ = load_house_style(args.skill)  # validate skill is readable
    template_text = template_path.read_text(encoding="utf-8").strip() if template_path.exists() else ""
    if not template_text:
        raise FileNotFoundError(f"Template not found or empty: {template_path}")
    system_instruction = compose_system_instruction(template_text, skill_text, args.kind)

    wanted = {slugify(v) for v in args.characters} if args.characters else None
    api_key = os.environ.get("GEMINI_API_KEY")
    args.request_dir.mkdir(parents=True, exist_ok=True)
    args.response_dir.mkdir(parents=True, exist_ok=True)

    generated = skipped = 0
    for character_dir in selected_dirs(args.characters_dir, wanted):
        name = character_dir.name
        cid = slugify(name)
        out_path = character_dir / f"{name.upper()}_{out_suffix}.md"
        request_path = args.request_dir / f"{cid}-{args.kind}.json"
        response_path = args.response_dir / f"{cid}-{args.kind}.txt"

        if out_path.exists() and not args.overwrite:
            print(f"Skipping {cid} ({args.kind}): {out_path.name} exists (use --overwrite)")
            skipped += 1
            continue

        facts_text = description_text = ""
        reference_sheet = None
        if args.kind == "description":
            if args.facts:
                facts_text = args.facts
            else:
                facts_file = find_facts_file(character_dir)
                if facts_file is None:
                    print(f"Skipping {cid}: no FACTS.md (or pass --facts)")
                    skipped += 1
                    continue
                facts_text = read_text(facts_file)
        else:
            desc_file = find_description_file(character_dir)
            if desc_file is None:
                print(f"Skipping {cid}: no *_DESCRIPTION.md yet (run --kind description first)")
                skipped += 1
                continue
            description_text = read_text(desc_file)
            candidate = character_dir / f"{cid}_character_sheet.jpg"
            reference_sheet = candidate if candidate.exists() else None

        references = images_in_subdir(character_dir, images_subdir)
        if not references:
            print(f"Skipping {cid}: no cut-outs in {images_subdir}/ (run prep_source_photos first)")
            skipped += 1
            continue

        input_blocks = build_input_blocks(args.kind, name, facts_text, description_text,
                                          references, reference_sheet)
        payload: dict[str, Any] = {
            "model": args.model,
            "input": input_blocks,
            "store": False,
            "system_instruction": system_instruction,
        }
        write_dry_run_request(request_path, payload)

        if not args.send:
            extra = " + reference sheet" if reference_sheet else ""
            print(f"Prepared {cid} {args.kind} request ({len(references)} cut-out(s){extra}): {request_path}")
            continue

        print(f"Generating {cid} {out_suffix}.md with {args.model}")
        response = post_json(payload, api_key=api_key, allow_proxy_auth=args.allow_proxy_auth)
        text = extract_text(response)
        if not text:
            response_path.write_text(str(redact_image_data(response))[:4000], encoding="utf-8")
            raise RuntimeError(f"No text returned for {cid} ({args.kind}); see {response_path}")
        out_path.write_text(text.rstrip() + "\n", encoding="utf-8")
        response_path.write_text(text, encoding="utf-8")
        print(f"Wrote {out_path}")
        generated += 1
        if args.sleep_seconds:
            time.sleep(args.sleep_seconds)

    if args.send:
        print(f"Generated {generated} {out_suffix}.md file(s). Skipped {skipped}.")
    else:
        print(f"Dry run prepared request(s). Skipped {skipped}. Pass --send to generate.")


if __name__ == "__main__":
    main()
